STUDENT MARKS PREDICTION MODEL

The Linear Regression model achieved an R² score of 0.81, meaning the model explains about 81% of the variation in students' final grades (G3). Features like G1 and G2 showed strong predictive power, indicating previous academic performance is the most important factor affecting final result

The Mean Absolute Error shows that the predicted final grade differs from the actual grade by approximately 1.29 marks on average, indicating good prediction accuracy of the model.

In [181]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error

In [159]:
df=pd.read_csv("Student_data.csv")

In [160]:
df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10

In [161]:
df.size

13035

In [162]:
df.columns

Index(['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
       'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime',
       'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery',
       'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc',
       'Walc', 'health', 'absences', 'G1', 'G2', 'G3'],
      dtype='str')

In [163]:
df.isnull().sum()

school        0
sex           0
age           0
address       0
famsize       0
Pstatus       0
Medu          0
Fedu          0
Mjob          0
Fjob          0
reason        0
guardian      0
traveltime    0
studytime     0
failures      0
schoolsup     0
famsup        0
paid          0
activities    0
nursery       0
higher        0
internet      0
romantic      0
famrel        0
freetime      0
goout         0
Dalc          0
Walc          0
health        0
absences      0
G1            0
G2            0
G3            0
dtype: int64

In [164]:
features=['age','traveltime','freetime','health','studytime','activities','internet','absences','G1','G2','failures']
df[features].describe()

,age,traveltime,freetime,health,studytime,absences,G1,G2,failures
count,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000
mean,16.696203,1.448101,3.235443,3.554430,2.035443,5.708861,10.908861,10.713924,0.334177
std,1.276043,0.697505,0.998862,1.390303,0.839240,8.003096,3.319195,3.761505,0.743651
min,15.000000,1.000000,1.000000,1.000000,1.000000,0.000000,3.000000,0.000000,0.000000
25%,16.000000,1.000000,3.000000,3.000000,1.000000,0.000000,8.000000,9.000000,0.000000
50%,17.000000,1.000000,3.000000,4.000000,2.000000,4.000000,11.000000,11.000000,0.000000
75%,18.000000,2.000000,4.000000,5.000000,2.000000,8.000000,13.000000,13.000000,0.000000
max,22.000000,4.000000,5.000000,5.000000,4.000000,75.000000,19.000000,19.000000,3.000000

In [169]:
le=LabelEncoder()
df['internet']=le.fit_transform(df['internet'])

In [166]:
df.activities.describe()

count    395.000000
mean       0.508861
std        0.500555
min        0.000000
25%        0.000000
50%        1.000000
75%        1.000000
max        1.000000
Name: activities, dtype: float64

In [170]:
df[features].corr()

,age,traveltime,freetime,health,studytime,activities,internet,absences,G1,G2,failures
age,1.000000,0.070641,0.016434,-0.062187,-0.004140,-0.103063,-0.112094,0.175230,-0.064081,-0.143474,0.243665
traveltime,0.070641,1.000000,-0.017025,0.007501,-0.100909,-0.007766,-0.111302,-0.012944,-0.093040,-0.153198,0.092239
freetime,0.016434,-0.017025,1.000000,0.075733,-0.143198,0.089728,0.051286,-0.058078,0.012613,-0.013777,0.091987
health,-0.062187,0.007501,0.075733,1.000000,-0.075616,0.023923,-0.080189,-0.029937,-0.073172,-0.097720,0.065827
studytime,-0.004140,-0.100909,-0.143198,-0.075616,1.000000,0.089877,0.059422,-0.062700,0.160612,0.135880,-0.173563
activities,-0.103063,-0.007766,0.089728,0.023923,0.089877,1.000000,0.048663,-0.013610,0.057010,0.050552,-0.069341
internet,-0.112094,-0.111302,0.051286,-0.080189,0.059422,0.048663,1.000000,0.101701,0.071619,0.119439,-0.063451
absences,0.175230,-0.012944,-0.058078,-0.029937,-0.062700,-0.013610,0.101701,1.000000,-0.031003,-0.031777,0.063726
G1,-0.064081,-0.093040,0.012613,-0.073172,0.160612,0.057010,0.071619,-0.031003,1.000000,0.852118,-0.354718
G2,-0.143474,-0.153198,-0.013777,-0.097720,0.135880,0.050552,0.119439,-0.031777,0.852118,1.000000,-0.355896
failures,0.243665,0.092239,0.091987,0.065827,-0.173563,-0.069341,-0.063451,0.063726,-0.354718,-0.355896,1.000000

In [171]:
df.failures.head()

0    0
1    0
2    3
3    0
4    0
Name: failures, dtype: int64

In [172]:
df.internet.describe()

count    395.000000
mean       0.832911
std        0.373528
min        0.000000
25%        1.000000
50%        1.000000
75%        1.000000
max        1.000000
Name: internet, dtype: float64

In [173]:
df.G3.max()

np.int64(20)

In [174]:
x=df[features]
y=df.G3

In [175]:
x_train,x_val,y_train,y_val=train_test_split(x,y,test_size=0.25,random_state=42)

In [176]:
model=LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [177]:
#features=['age','traveltime','freetime','health','studytime','activities','internet','absences','G1','G2','failures']

model.predict([[13,2,1,2,8,1,1,0,10,15,0]])

c:\Users\raju1\OneDrive\Desktop\Projects\Student performance predictor\venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([14.47266876])

In [182]:
pred=model.predict(x_val)
acc=r2_score(y_val,pred)
print(acc*100)
mae=mean_absolute_error(y_val,pred)
print(mae)
mse=mean_squared_error(y_val,pred)
print(mse)

81.1442074637734
1.2856633083055153
4.343969819329404

In [179]:
a=int(input("Enterageofstudetna:"))

In [180]:
print(a)

21