STUDENT MARKS PREDICTION MODEL

The Linear Regression model achieved an R² score of 0.81, meaning the model explains about 81% of the variation in students' final grades (G3). Features like G1 and G2 showed strong predictive power, indicating previous academic performance is the most important factor affecting final result

The Mean Absolute Error shows that the predicted final grade differs from the actual grade by approximately 1.29 marks on average, indicating good prediction accuracy of the model.

In [3]:
import numpy as np
import pandas as pd
import joblib
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error

In [4]:
df=pd.read_csv("Student_data.csv")

In [5]:
df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10

In [6]:
df.size

13035

In [7]:
df.columns

Index(['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
       'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime',
       'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery',
       'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc',
       'Walc', 'health', 'absences', 'G1', 'G2', 'G3'],
      dtype='str')

In [8]:

df['goout'].unique()

array([4, 3, 2, 1, 5])

In [13]:
features=['goout','sex','traveltime','health','studytime','activities','internet','absences','G1','G2','failures','romantic']
df[features].corr()

,goout,sex,traveltime,health,studytime,activities,internet,absences,G1,G2,failures,romantic
goout,1.000000,0.075897,0.028540,-0.009577,-0.063904,0.046088,0.074370,0.044302,-0.149104,-0.162250,0.124561,0.007870
sex,0.075897,1.000000,0.059722,0.143588,-0.306268,0.099833,0.044113,-0.066962,0.091839,0.091099,0.044436,-0.102023
traveltime,0.028540,0.059722,1.000000,0.007501,-0.100909,-0.007766,-0.111302,-0.012944,-0.093040,-0.153198,0.092239,0.021962
health,-0.009577,0.143588,0.007501,1.000000,-0.075616,0.023923,-0.080189,-0.029937,-0.073172,-0.097720,0.065827,0.026342
studytime,-0.063904,-0.306268,-0.100909,-0.075616,1.000000,0.089877,0.059422,-0.062700,0.160612,0.135880,-0.173563,0.053285
activities,0.046088,0.099833,-0.007766,0.023923,0.089877,1.000000,0.048663,-0.013610,0.057010,0.050552,-0.069341,0.019651
internet,0.074370,0.044113,-0.111302,-0.080189,0.059422,0.048663,1.000000,0.101701,0.071619,0.119439,-0.063451,0.087122
absences,0.044302,-0.066962,-0.012944,-0.029937,-0.062700,-0.013610,0.101701,1.000000,-0.031003,-0.031777,0.063726,0.153384
G1,-0.149104,0.091839,-0.093040,-0.073172,0.160612,0.057010,0.071619,-0.031003,1.000000,0.852118,-0.354718,-0.037188
G2,-0.162250,0.091099,-0.153198,-0.097720,0.135880,0.050552,0.119439,-0.031777,0.852118,1.000000,-0.355896,-0.111774
failures,0.124561,0.044436,0.092239,0.065827,-0.173563,-0.069341,-0.063451,0.063726,-0.354718,-0.355896,1.000000,0.093137
romantic,0.007870,-0.102023,0.021962,0.026342,0.053285,0.019651,0.087122,0.153384,-0.037188,-0.111774,0.093137,1.000000

In [12]:
le=LabelEncoder()
df['internet']=le.fit_transform(df['internet'])
df['activities']=le.fit_transform(df['activities'])
df['romantic']=le.fit_transform(df['romantic'])
df['school']=le.fit_transform(df['school'])
df['sex']=le.fit_transform(df['sex'])
df['famsize']=le.fit_transform(df['famsize'])

In [ ]:
df.activities.describe()

count     395
unique      2
top       yes
freq      201
Name: activities, dtype: object

In [ ]:
df[features].corr()

,Medu,Fedu,age,traveltime,freetime,health,studytime,activities,internet,absences,G1,G2,failures,romantic
Medu,1.000000,0.623455,-0.163658,-0.171639,0.030891,-0.046878,0.064944,0.108277,0.201463,0.100285,0.205341,0.215527,-0.236680,0.039681
Fedu,0.623455,1.000000,-0.163438,-0.158194,-0.012846,0.014742,-0.009175,0.112643,0.127507,0.024473,0.190270,0.164893,-0.250408,0.015602
age,-0.163658,-0.163438,1.000000,0.070641,0.016434,-0.062187,-0.004140,-0.103063,-0.112094,0.175230,-0.064081,-0.143474,0.243665,0.164669
traveltime,-0.171639,-0.158194,0.070641,1.000000,-0.017025,0.007501,-0.100909,-0.007766,-0.111302,-0.012944,-0.093040,-0.153198,0.092239,0.021962
freetime,0.030891,-0.012846,0.016434,-0.017025,1.000000,0.075733,-0.143198,0.089728,0.051286,-0.058078,0.012613,-0.013777,0.091987,-0.011182
health,-0.046878,0.014742,-0.062187,0.007501,0.075733,1.000000,-0.075616,0.023923,-0.080189,-0.029937,-0.073172,-0.097720,0.065827,0.026342
studytime,0.064944,-0.009175,-0.004140,-0.100909,-0.143198,-0.075616,1.000000,0.089877,0.059422,-0.062700,0.160612,0.135880,-0.173563,0.053285
activities,0.108277,0.112643,-0.103063,-0.007766,0.089728,0.023923,0.089877,1.000000,0.048663,-0.013610,0.057010,0.050552,-0.069341,0.019651
internet,0.201463,0.127507,-0.112094,-0.111302,0.051286,-0.080189,0.059422,0.048663,1.000000,0.101701,0.071619,0.119439,-0.063451,0.087122
absences,0.100285,0.024473,0.175230,-0.012944,-0.058078,-0.029937,-0.062700,-0.013610,0.101701,1.000000,-0.031003,-0.031777,0.063726,0.153384
G1,0.205341,0.190270,-0.064081,-0.093040,0.012613,-0.073172,0.160612,0.057010,0.071619,-0.031003,1.000000,0.852118,-0.354718,-0.037188
G2,0.215527,0.164893,-0.143474,-0.153198,-0.013777,-0.097720,0.135880,0.050552,0.119439,-0.031777,0.852118,1.000000,-0.355896,-0.111774
failures,-0.236680,-0.250408,0.243665,0.092239,0.091987,0.065827,-0.173563,-0.069341,-0.063451,0.063726,-0.354718,-0.355896,1.000000,0.093137
romantic,0.039681,0.015602,0.164669,0.021962,-0.011182,0.026342,0.053285,0.019651,0.087122,0.153384,-0.037188,-0.111774,0.093137,1.000000

In [ ]:
df.failures.head()

0    0
1    0
2    3
3    0
4    0
Name: failures, dtype: int64

In [ ]:
df.internet.describe()

count    395.000000
mean       0.832911
std        0.373528
min        0.000000
25%        1.000000
50%        1.000000
75%        1.000000
max        1.000000
Name: internet, dtype: float64

In [ ]:
df.G3.max()

np.int64(20)

In [ ]:
x=df[features]
y=df.G3

In [ ]:
x_train,x_val,y_train,y_val=train_test_split(x,y,test_size=0.25,random_state=42)

In [ ]:
model=LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [ ]:
#features=['age','traveltime','freetime','health','studytime','activities','internet','absences','G1','G2','failures']

model.predict([[4,4,13,2,1,2,8,1,1,0,10,15,0,0]])

c:\Users\raju1\OneDrive\Desktop\Projects\Student performance predictor\venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([14.27826223])

In [ ]:
pred=model.predict(x_val)
acc=r2_score(y_val,pred)
print(acc*100)
mae=mean_absolute_error(y_val,pred)
print(mae)
mse=mean_squared_error(y_val,pred)
print(mse)

80.90034386153616
1.2962039250737711
4.400150758216821

In [ ]:
a=int(input("Enterageofstudetna:"))

In [ ]:
print(a)

21

In [ ]:
joblib.dump({
    "model": model,
    "encoder": le
}, "model.pkl")

['model.pkl']